# Generated by Django 3.1.6 on 2021-02-24 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ManyToManyField(related_name='_clientprofile_owner_+',
                                                 related_query_name='clients', to='CRM.ClientProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.FileField(upload_to='contracts/%Y/%m/%d/')),
                ('description', models.CharField(max_length=200)),
                ('lat', models.FloatField(max_length=6)),
                ('long', models.FloatField(max_length=6)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='businesses', to='CRM.clientprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
