# Generated by Django 3.1.6 on 2021-02-24 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_remove_clientprofile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='employers',
            field=models.ManyToManyField(related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
