# Generated by Django 3.1.6 on 2021-02-26 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_clientprofile_employers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_client',
            new_name='is_tenant',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_owner',
            new_name='is_landlord',
        ),
        migrations.RemoveField(
            model_name='business',
            name='client',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner',
        ),
        migrations.AddField(
            model_name='business',
            name='landlord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='lands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='name',
            field=models.CharField(default='Land', max_length=100),
            preserve_default=False,
        ),

        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='landlords',
            field=models.ManyToManyField(
                related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='lands', to='CRM.tenantprofile'),
        ),
    ]
