# Generated by Django 3.1.6 on 2021-02-26 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_auto_20210226_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='landlords',
            field=models.ManyToManyField(related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_tenant',
            field=models.BooleanField(default=True),
        ),
    ]
