# Generated by Django 3.1.6 on 2021-02-26 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_auto_20210226_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantprofile',
            old_name='user',
            new_name='tenant',
        ),
        migrations.AlterField(
            model_name='business',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='CRM.tenantprofile'),
        ),
    ]
