# Generated by Django 3.1.6 on 2021-02-26 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_auto_20210226_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='landlords',
            field=models.ManyToManyField(related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
    ]
