# Generated by Django 3.1.6 on 2021-03-01 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_auto_20210226_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.CharField(max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='business',
            name='lat',
            field=models.FloatField(verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='business',
            name='long',
            field=models.FloatField(verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='business',
            name='tenant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='CRM.tenantprofile', verbose_name='tenant'),
        ),
    ]
