# Generated by Django 3.1.6 on 2021-03-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_auto_20210301_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
