# Generated by Django 3.1.6 on 2021-03-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0012_auto_20210301_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='contract',
            field=models.FileField(blank=True, upload_to='contracts/%Y/%m/%d/'),
        ),
    ]
