# Generated by Django 3.1.6 on 2021-03-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0014_auto_20210302_0937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Business',
            new_name='Land',
        ),
    ]
