# Generated by Django 3.1.6 on 2021-03-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0016_auto_20210302_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='land',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='CRM.land', verbose_name='land'),
        ),
    ]
