# Generated by Django 3.1.6 on 2021-03-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0017_auto_20210302_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='owed',
            field=models.FloatField(default=0, verbose_name='payed'),
            preserve_default=False,
        ),
    ]
