# Generated by Django 3.1.6 on 2021-03-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0018_billing_owed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='owed',
            field=models.FloatField(verbose_name='owed'),
        ),
    ]
