# Generated by Django 3.1.6 on 2021-03-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0019_auto_20210303_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='plan',
            field=models.ImageField(blank=True, upload_to='plans/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.CharField(max_length=300, verbose_name='description'),
        ),
    ]
