# Generated by Django 3.1.6 on 2021-03-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0020_auto_20210304_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='plan',
        ),
        migrations.AddField(
            model_name='land',
            name='location_url',
            field=models.URLField(default='', verbose_name='google maps link'),
            preserve_default=False,
        ),
    ]
