# Generated by Django 3.1.6 on 2021-03-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0023_auto_20210304_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='map_src',
        ),
        migrations.AddField(
            model_name='land',
            name='map_link',
            field=models.URLField(default='https://goo.gl/maps/ECSqfSAgo3B4jqCF6', verbose_name='google maps link'),
            preserve_default=False,
        ),
    ]
