# Generated by Django 3.1.6 on 2021-03-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0026_land_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='hectares',
            field=models.IntegerField(default=100, verbose_name='hectares'),
            preserve_default=False,
        ),
    ]
