# Generated by Django 3.1.6 on 2021-03-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0028_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_request',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
