# Generated by Django 4.0.2 on 2022-02-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0029_message_is_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='land',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
